name: ml-zoomcamp

dependencies:
    - python==3.8
    - pip==21.2.2
    
    - pip:
      - numpy
      - pandas
      - matplotlib
      - tensorflow
      - scikit-learn 
      - jupyterlab
      - xgboost
    
  